from tkinter import * #引用Tk模块
root = Tk() #初始化Tk()
root.title("发邮件")
frm = Frame(root)
root.geometry('470x280')
frm_S = Frame(frm)
Button(frm_S, text="发送", width=6, height=1, font=('Arial', 10)).pack(side=LEFT)
Button(frm_S, text="重置", width=6, height=1, font=('Arial', 10)).pack(side=RIGHT)
frm_S.pack(side=TOP)
frm_L = Frame(frm)
frm_LT = Frame(frm_L)
Label(frm_LT, text = '发件人', font =('Arial',12)).pack(side=TOP)
Label(frm_LT, text = '接收人', font =('Arial',12)).pack(side=TOP)
Label(frm_LT, text = ' 题目', font =('Arial',12)).pack(side=TOP)
frm_LT.pack(side=LEFT)
frm_RT= Frame(frm_L)
var_sender=StringVar()
var_title = StringVar()
var_receiver = StringVar()
Entry(frm_RT,textvariable=var_sender, width = 30,font =('Verdana',15)).pack()
Entry(frm_RT,textvariable= var_receiver, width = 30,font =('Verdana',15)).pack()
Entry(frm_RT,textvariable= var_title, width = 30,font =('Verdana',15)).pack()
frm_RT.pack(side=RIGHT)
frm_L.pack(side=TOP)
#third-label
frm_ConText = Frame(frm)
Label(frm_ConText, text = '发送内容', font =('Arial',12)).pack(side=TOP)
frm_ConText.pack(side=TOP)
#forth-inputcontext
frm_M = Frame(frm)
t_show = Text(frm_M, width=34, height=6, font=('Verdana',15))
t_show.insert('1.0', 'Hello, Calvin')
t_show.pack()
frm_M.pack()
frm.pack()
root.mainloop()